### PR TITLE
Update to latest hexo version, node 14.0.0 minimum required (fix #533)

### LINKED ISSUE #533: Update version of the site generator hexo
We currently use hexo 3.2.2, although the build seems to work fine on node 22, we may try to update the hexo version, see
https://hexo.io/docs/#Required-Node-js-version

### PR DESCRIPTION
**Pull request by vincentfretin**
This closes #533

The github version of hexo-renderer-marked we used was for this PR that was merged https://github.com/hexojs/hexo-renderer-marked/pull/24 so latest version include the lowercase anchors.
sanitize and tables options are deprecated, sanitize was false, and tables is now included with gfm option, see
https://github.com/hexojs/hexo-renderer-marked/releases/tag/2.0.0

hexo-generator-feed I kept it to 1.2.0, I tested more recent version but got an error.
I tested the feed is correctly rendered when I go to http://localhost:4000/feed.xml

hexo-filter-github-emojis I pinned the version to 1.4.4. I didn't test more recent version.

All the other plugins are the latest version.

Reading https://hexo.io/docs/one-command-deployment#Git the deploy key is repo, not repository.

I read all the changelogs and README, I didn't see any other breaking change worth mentioning for our use here.

### CODE REVIEW

**Comment by vincentfretin** [comment]
FYI I tested with node v22.3.0.

**Comment by vincentfretin** [comment]
I guess we don't really use the hexo-deployer-git plugin, but custom commands, see
https://github.com/supermedium/a-frobot/blob/master/lib/deployAframeSite.js#L35-L38

**Comment by vincentfretin** [comment]
I guess we wait to update the robot as well https://github.com/supermedium/a-frobot/issues/2 before merging this PR.

**Comment by dmarcos** [comment]
Thanks

**Pull request merged**
