### PR TITLE
Added list of users that are using A-Frame in 'production' to community page.

### PR DESCRIPTION
**Pull request by RCMainak**
Fixes issue #414.

Things needs attention,
- I can't find the logo for 360syria project.
- I don't like how the page looks currently
- All the logos are not of same size and hosted on different third party servers including twitter and linkedin.

Any suggestion will be appreciated.

### CODE REVIEW

**Comment by dmarcos** [comment]
Thanks! It looks good to me. I let @ngokevin since he knows this better than me.

**Comment by RCMainak** [comment]
@ngokevin any updates???

**Comment by mukeshpathak345** [comment]
Hello WebVR india

**Comment by ngokevin** [comment]
Hey, sorry for not responding. Thanks for the work you put in. I've since added a Showcase page that's more updated now. https://aframe.io/showcase/

**Pull request closed without merging**
