### PR TITLE
use docs from aframe repo (fixes #123)

### LINKED ISSUE #123: Render docs from aframe repo
Originally, we had the docs live in separate places and have them moved over to a single repo in the interest of time (editing, rebuilding, previewing, etc.).

I have a simple architecture I want to do for the docs.

And it allows us to have the `.md` docs live anywhere but the `/docs/` site sources them all and renders them nicely. I did this for the original "Kit" I made (forked from [Flatdoc](ricostacruz.com/flatdoc/)). It doesn't have to be a single page. I've got a few of the pieces locally; it's quite, quite nice.

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by cvan** [comment]
and I actually have a couple ideas on how to version the docs (#121)

**Comment by ngokevin** [comment]
I like it. Would like to know ideas on versioning.

Thanks so so much for looking at this.

**Comment by ngokevin** [comment]
Note that the relative links in the A-Frame repo have ```.md``` suffixes so they can be browsed through the GitHub interface. Those will need to be replaced with ```.html```.

**Comment by cvan** [comment]
> Note that the relative links in the A-Frame repo have ```.md``` suffixes so they can be browsed through the GitHub interface. Those will need to be replaced with ```.html```.

thanks for catching that. I can fix that with a Hexo template hook.

**Comment by cvan** [comment]
woooot! :tada:

**Pull request merged**
