### PR TITLE
tidy up typography and margins (at both desktop and mobile widths)

### PR DESCRIPTION
**Pull request by cvan**
## before
screen shot 2016-08-30 at 8 46 30 pm
## after
screen shot 2016-08-30 at 8 46 14 pm

<br><hr><br>

## before
screen shot 2016-08-30 at 10 46 05 pm
## after
screen shot 2016-08-30 at 8 47 44 pm

<br><hr><br>

## before
screen shot 2016-08-30 at 8 47 57 pm
## after
screen shot 2016-08-30 at 8 58 00 pm

<br><hr><br>

## before
screen shot 2016-08-30 at 8 58 22 pm
## after
screen shot 2016-08-30 at 8 58 43 pm

<br><hr><br>

## before
screen shot 2016-08-30 at 8 59 22 pm
## after
screen shot 2016-08-30 at 8 59 33 pm

## before
screen shot 2016-08-30 at 8 59 44 pm
## after
screen shot 2016-08-30 at 8 59 52 pm

### CODE REVIEW

**Comment by cvan** [comment]
ping r? @ngokevin

**Comment by ngokevin** [comment]
seems a bit inconsistent to remove "Blog" header but keep for "Community"

i think for your last two mobile screenshots, before / after are reversed right?

r+wc

**Comment by cvan** [comment]
> seems a bit inconsistent to remove "Blog" header but keep for "Community"

yes, good call

**Comment by cvan** [comment]
> i think for your last two mobile screenshots, before / after are reversed right?

yep, my bad

**Pull request merged**
