### PR TITLE
Losslessly crunch image size

### PR DESCRIPTION
**Pull request by darkwing**
I used ImageOptim for lossless image compression.  30MB savings:

losslessimagecrunch

Should lighten site load

### CODE REVIEW

**Comment by cvan** [comment]
I've had pngquant turn up better results. I believe ImageOptim uses pngcrush w/ some settings under the hood which isn't always lossless. Do you know?

**Comment by cvan** [comment]
because there are so many images, a lot of the diffs aren't shown. but of those ones that are shown, I can't discern the difference (at a glance). thanks! will take a closer look in a bit.

**Comment by ngokevin** [comment]
Whatever is decided, there is a script in `src/images/awoa/_process-images` that I run, you can update that.

**Comment by cvan** [comment]
@darkwing want to update the script? I've used some npm build scripts with good success in the past to automate this. in fact, I introduced one in https://github.com/aframevr/aframe-site/pull/319 - but I have to fix up that PR a bit so it doesn't run the command during development (should be run only during deploys).

**Comment by darkwing** [comment]
Been buried in MozReview work and interviews, working on this now.

**Comment by darkwing** [comment]
I think we should close this in favor of https://github.com/aframevr/aframe-site/pull/319 ; this was meant as a quick win but the other PR is a longer lasting solution.

**Comment by darkwing** [comment]
I was also playing with other utilities and none of their node counterparts was doing as well as the Mac App, so the permanent hexo solution will be better.

**Pull request closed without merging**
