### PR TITLE
[WIP] search (lunr)

### PR DESCRIPTION
**Pull request by ngokevin**
have to create my own lunr hexo generator to lower the search bundle.

### CODE REVIEW

**Comment by ngokevin** [comment]
This is working, but not very satisfying (big bundle, can't display matched excerpt in the document). Looking at Algolia.

**Comment by cvan** [comment]
You can use lunr.js with a Node server, fwiw. There are probably a ton of better libs out there these days too. I checked out a few, but I'm surprised there aren't more hosted elasticsearch solutions.

Perhaps try these two if not Algolia?

https://www.elastic.co/cloud/as-a-service/signup
https://github.com/asciimoo/searx

**Comment by ngokevin** [comment]
The way Lunr indexes files is geared for the client. The Node package handles indexing, but there's not really a Lunr server as a service.

Anything wrong with Algolia? Seems most out-of-the-box (just shove it data and go). Used by HackerNews/React/Vue.js. The free tier looks like it'll work fine for now. Currently playing with it.

**Comment by ngokevin** [comment]
Dang it, just found https://community.algolia.com/docsearch/ after getting Algolia up from scratch.

**Pull request closed without merging**
